name = "DecoratedParticles"
uuid = "023d0394-cb16-4d2d-a5c7-724bed42bbb6"
authors = ["Christoph Ortner <christohortner@gmail.com> and contributors"]
version = "0.0.1-dev"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
